[package]
name = "minecrust"
version = "0.1.0"
authors = ["Christopher Fu <chrisf1337@gmail.com>"]
edition = "2018"

[dependencies]
gl = "*"
glutin = "*"
image = "*"
failure = "*"
failure_derive = "*"
nalgebra = "*"
specs = "*"
specs-derive = "*"
num-traits = "*"
