[package]
name = "minecrust"
version = "0.1.0"
authors = ["Christopher Fu <chrisf1337@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
gl = "*"
glutin = "*"
image = "*"
failure = "*"
failure_derive = "*"
nalgebra = "*"
specs = "*"
specs-derive = "*"
num-traits = "*"
alga = "*"
ash = "*"
winit = { git = "https://github.com/tomaka/winit.git" }
byteorder = "*"
freetype = "*"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "*"
